#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"


  case "$(uname -s)" in
    Darwin)
      local url_mongodb='https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.0.7.tgz'
      local tmp_download="$(mktemp -t XXXXXX)"
      curl -L -o - "$url_mongodb" > "$tmp_download"
      mkdir -p vendor
      cd vendor
      tar xvfz "$tmp_download"
      ln -nfs mongodb-osx-x86_64-3.0.7 mongodb
      ;;
    *)
      true
      ;;
  esac
}

bootstrap
